### ISSUE TITLE
Extra GUI aesthetic features (Brenden)

### ISSUE THREAD

**Issue by tosh1100** [csaben/CPSC-Group-Project#7]
In difficulty order:
1. When in continuous scrolling mode, bold chapter names descriptions
2. Change buttons to interesting fantasy looking buttons. Pretty sure you just put the image for the buttons in the local directory and replace "next"/"prev" with the image name 
3. Add some sort of interesting fantasy looking line break image to the chapter breaks when in continuous scrolling

**Comment by brendenhigh** [comment]
Put images in the next and previous buttons.

**Comment by brendenhigh** [comment]
I have changed the images to the arrows that you wanted.

**Comment by brendenhigh** [comment]
Arrows are the right size now and the next and prev have been removed to make the buttons look better.
